### ISSUE TITLE
Error in Sidebar component

### ISSUE THREAD

**Issue by avromanov2009** [i-mastymas/tr-web#13]
![image](https://user-images.githubusercontent.com/1846296/57828943-fa155a00-77b5-11e9-9d9e-09fd9d6d1130.png)
Code:
![image](https://user-images.githubusercontent.com/1846296/57828986-27fa9e80-77b6-11e9-9d82-648a2a3cce6e.png)

**Comment by ness-anastasiya** [comment]
Сюда нужно будет дописать маршруты, когда страницы будут готовы, пока их нет, это просто шаблон
